import type { CustomThemeConfig } from "../types/customTheme.types";

const base = (partial: Omit<CustomThemeConfig, "id"> & { id?: string }): CustomThemeConfig => ({
  id: partial.id ?? `theme-${Date.now()}`,
  name: partial.name,
  colors: partial.colors,
  effects: partial.effects,
  typography: partial.typography,
});

export const THEME_PRESETS: CustomThemeConfig[] = [
  base({
    id: "aurora",
    name: "Aurora Borealis",
    colors: {
      background: "#030712",
      backgroundAlt: "#0c1929",
      surface: "rgba(12, 25, 41, 0.72)",
      accent: "#22d3ee",
      accentSecondary: "#a78bfa",
      text: "#f0f9ff",
      textMuted: "#94a3b8",
      success: "#34d399",
    },
    effects: {
      gradientAngle: 135,
      glowIntensity: 65,
      glassBlur: 16,
      borderRadius: 16,
      animatedGradient: true,
      meshGradient: true,
      neonGlow: true,
      noiseOverlay: true,
      starfield: true,
    },
    typography: "display",
  }),
  base({
    id: "cyber-neon",
    name: "Cyber Neon",
    colors: {
      background: "#0a0a0f",
      backgroundAlt: "#12121a",
      surface: "rgba(18, 18, 26, 0.85)",
      accent: "#ff00ff",
      accentSecondary: "#00ffff",
      text: "#fafafa",
      textMuted: "#a1a1aa",
      success: "#00ff88",
    },
    effects: {
      gradientAngle: 90,
      glowIntensity: 90,
      glassBlur: 12,
      borderRadius: 8,
      animatedGradient: true,
      meshGradient: false,
      neonGlow: true,
      noiseOverlay: true,
      starfield: false,
    },
    typography: "mono",
  }),
  base({
    id: "ocean-deep",
    name: "Deep Ocean",
    colors: {
      background: "#021526",
      backgroundAlt: "#033052",
      surface: "rgba(3, 48, 82, 0.6)",
      accent: "#38bdf8",
      accentSecondary: "#2dd4bf",
      text: "#e0f2fe",
      textMuted: "#7dd3fc",
      success: "#4ade80",
    },
    effects: {
      gradientAngle: 160,
      glowIntensity: 45,
      glassBlur: 20,
      borderRadius: 20,
      animatedGradient: true,
      meshGradient: true,
      neonGlow: false,
      noiseOverlay: false,
      starfield: true,
    },
    typography: "system",
  }),
  base({
    id: "volcanic",
    name: "Volcanic Ember",
    colors: {
      background: "#1a0505",
      backgroundAlt: "#2d0a0a",
      surface: "rgba(45, 10, 10, 0.75)",
      accent: "#f97316",
      accentSecondary: "#ef4444",
      text: "#fff7ed",
      textMuted: "#fdba74",
      success: "#86efac",
    },
    effects: {
      gradientAngle: 45,
      glowIntensity: 70,
      glassBlur: 10,
      borderRadius: 14,
      animatedGradient: true,
      meshGradient: true,
      neonGlow: true,
      noiseOverlay: true,
      starfield: false,
    },
    typography: "serif",
  }),
  base({
    id: "enchanted",
    name: "Enchanted Forest",
    colors: {
      background: "#041208",
      backgroundAlt: "#0a1f0f",
      surface: "rgba(10, 31, 15, 0.7)",
      accent: "#84cc16",
      accentSecondary: "#a3e635",
      text: "#ecfccb",
      textMuted: "#bef264",
      success: "#4ade80",
    },
    effects: {
      gradientAngle: 120,
      glowIntensity: 50,
      glassBlur: 14,
      borderRadius: 18,
      animatedGradient: false,
      meshGradient: true,
      neonGlow: false,
      noiseOverlay: true,
      starfield: true,
    },
    typography: "serif",
  }),
  base({
    id: "galaxy",
    name: "Midnight Galaxy",
    colors: {
      background: "#0b0b1a",
      backgroundAlt: "#151530",
      surface: "rgba(21, 21, 48, 0.8)",
      accent: "#818cf8",
      accentSecondary: "#c084fc",
      text: "#eef2ff",
      textMuted: "#a5b4fc",
      success: "#6ee7b7",
    },
    effects: {
      gradientAngle: 200,
      glowIntensity: 55,
      glassBlur: 18,
      borderRadius: 16,
      animatedGradient: true,
      meshGradient: true,
      neonGlow: true,
      noiseOverlay: false,
      starfield: true,
    },
    typography: "display",
  }),
  base({
    id: "sakura",
    name: "Sakura Dream",
    colors: {
      background: "#1a0a14",
      backgroundAlt: "#2d1525",
      surface: "rgba(45, 21, 37, 0.75)",
      accent: "#f472b6",
      accentSecondary: "#fb7185",
      text: "#fdf2f8",
      textMuted: "#f9a8d4",
      success: "#86efac",
    },
    effects: {
      gradientAngle: 315,
      glowIntensity: 60,
      glassBlur: 16,
      borderRadius: 22,
      animatedGradient: true,
      meshGradient: true,
      neonGlow: true,
      noiseOverlay: true,
      starfield: false,
    },
    typography: "display",
  }),
  base({
    id: "holo",
    name: "Holo Prism",
    colors: {
      background: "#0f0f14",
      backgroundAlt: "#1a1a24",
      surface: "rgba(26, 26, 36, 0.65)",
      accent: "#e879f9",
      accentSecondary: "#67e8f9",
      text: "#faf5ff",
      textMuted: "#d8b4fe",
      success: "#a3e635",
    },
    effects: {
      gradientAngle: 270,
      glowIntensity: 80,
      glassBlur: 22,
      borderRadius: 12,
      animatedGradient: true,
      meshGradient: true,
      neonGlow: true,
      noiseOverlay: true,
      starfield: true,
    },
    typography: "mono",
  }),
];

export const DEFAULT_CUSTOM_THEME = THEME_PRESETS[0];

export const randomTheme = (): CustomThemeConfig => {
  const hue = Math.floor(Math.random() * 360);
  const hue2 = (hue + 60 + Math.floor(Math.random() * 120)) % 360;
  return base({
    name: `Cosmic ${Math.floor(Math.random() * 900 + 100)}`,
    colors: {
      background: `hsl(${hue}, 30%, 6%)`,
      backgroundAlt: `hsl(${hue}, 35%, 12%)`,
      surface: `hsla(${hue}, 40%, 18%, 0.7)`,
      accent: `hsl(${hue}, 85%, 60%)`,
      accentSecondary: `hsl(${hue2}, 80%, 65%)`,
      text: "#f8fafc",
      textMuted: `hsl(${hue}, 20%, 65%)`,
      success: "#4ade80",
    },
    effects: {
      gradientAngle: Math.floor(Math.random() * 360),
      glowIntensity: 40 + Math.floor(Math.random() * 50),
      glassBlur: 8 + Math.floor(Math.random() * 14),
      borderRadius: 8 + Math.floor(Math.random() * 16),
      animatedGradient: Math.random() > 0.3,
      meshGradient: Math.random() > 0.4,
      neonGlow: Math.random() > 0.35,
      noiseOverlay: Math.random() > 0.5,
      starfield: Math.random() > 0.5,
    },
    typography: (["system", "mono", "serif", "display"] as const)[Math.floor(Math.random() * 4)],
  });
};
